In [7]:
import tensorflow as tf

# sess = tf.Session()

x = tf.one_hot( [[0], [1], [2], [3]], depth =3)
with sess.as_default() :
    print(tf.one_hot( [[0], [1], [2], [3]], depth =3))
    print(sess.run(x))

Tensor("one_hot_8:0", shape=(4, 1, 3), dtype=float32)
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[0. 0. 0.]]]


In [10]:
sample ="if you want me"
idx2char=list(set(sample))
char2idx = { c: i for i, c in enumerate(idx2char)}
idx2char


['a', 'o', 'w', 't', ' ', 'e', 'f', 'm', 'u', 'i', 'n', 'y']

In [11]:
char2idx

{'a': 0,
 'o': 1,
 'w': 2,
 't': 3,
 ' ': 4,
 'e': 5,
 'f': 6,
 'm': 7,
 'u': 8,
 'i': 9,
 'n': 10,
 'y': 11}

In [12]:
sample_idx = [char2idx[c] for c in sample]
sample_idx

[9, 6, 4, 11, 1, 8, 4, 2, 0, 10, 3, 4, 7, 5]

In [14]:
x_data = [sample_idx[ : -1]]
x_data

[[9, 6, 4, 11, 1, 8, 4, 2, 0, 10, 3, 4, 7]]

In [2]:
tf.one_hot( [[0], [1], [2], [3]], depth =3)

<tf.Tensor 'one_hot:0' shape=(4, 1, 3) dtype=float32>

In [4]:
t=tf.one_hot( [[0], [1], [2], [3]], depth =3)
print(t.shape)

(4, 1, 3)


In [5]:
print(t)

Tensor("one_hot_2:0", shape=(4, 1, 3), dtype=float32)


In [6]:
t

<tf.Tensor 'one_hot_2:0' shape=(4, 1, 3) dtype=float32>

In [18]:
print(tf.one_hot( [[0], [1], [2], [3]], depth =3))

Tensor("one_hot_7:0", shape=(4, 1, 3), dtype=float32)


In [5]:
sess = tf.Session()
sess.run(t)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[0., 0., 0.]]], dtype=float32)

In [10]:
t=tf.one_hot( [[0], [1], [2], [3]], depth =2)
sess.run(t)

array([[[1., 0.]],

       [[0., 1.]],

       [[0., 0.]],

       [[0., 0.]]], dtype=float32)

In [19]:
tf.reshape( t, shape=[ -1, 3])

<tf.Tensor 'Reshape_2:0' shape=(4, 3) dtype=float32>

In [20]:
sess.run(tf.reshape( t, shape=[ -1, 3]))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)

In [26]:
a = [1, 4]
b = [2, 5]
c = [3, 6]
t=tf.stack([a, b, c])
t

<tf.Tensor 'stack_5:0' shape=(3, 2) dtype=int32>

In [27]:
sess.run(t)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
sess.run(tf.stack([a, b, c], axis=1))

array([[1, 2, 3],
       [4, 5, 6]])