In [1]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
import tensorflow as tf

x=[[1, 1, 1],
  [1, 1, 1]]

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
tf.rank(x).eval(sess=session)

NameError: name 'session' is not defined

In [5]:
import tensorflow as tf

x = tf.constant([[1., 2.], [3., 4.]])

sess = tf.Session()

print(sess.run(x))
print(sess.run(tf.reduce_mean(x)))
print(sess.run(tf.reduce_mean(x, 0)))
print(sess.run(tf.reduce_mean(x, 1)))

sess.close()

[[1. 2.]
 [3. 4.]]
2.5
[2. 3.]
[1.5 3.5]


In [7]:
t=tf.one_hot ([[0], [1], [2], [3] ], depth= 4)

In [8]:
sess.run(t)

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]]], dtype=float32)

In [5]:
sess = tf.Session()

In [2]:
x_data = [[1, 2, 1, 1],           [2, 1, 3, 2],
          [3, 1, 3, 4],           [4, 1, 5, 5],
          [1, 7, 5, 5],           [1, 2, 5, 6],
          [1, 6, 6, 6],           [1, 7, 7, 7]]
y_data = [[0, 0, 1],           [0, 0, 1],
          [0, 0, 1],           [0, 1, 0],
          [0, 1, 0],           [0, 1, 0],
          [1, 0, 0],           [1, 0, 0]]


In [3]:
x_data

[[1, 2, 1, 1],
 [2, 1, 3, 2],
 [3, 1, 3, 4],
 [4, 1, 5, 5],
 [1, 7, 5, 5],
 [1, 2, 5, 6],
 [1, 6, 6, 6],
 [1, 7, 7, 7]]

In [4]:
print(x_data)

[[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]


In [5]:
tf.shape(x_data)

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [12]:
y_data = [[0, 0, 1],           [0, 0, 1],
          [0, 0, 1],           [0, 1, 0],
          [0, 1, 0],           [0, 1, 0],
          [1, 0, 0],           [1, 0, 0]]


In [14]:
y_data

[[0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0]]

In [8]:
t=[-11,-11]

In [9]:
t

[-11, -11]

In [24]:
tf.shape(t)

<tf.Tensor 'Shape_5:0' shape=(1,) dtype=int32>

In [25]:
print(t.shape)

AttributeError: 'list' object has no attribute 'shape'

In [15]:
tf.shape(y_data)

<tf.Tensor 'Shape_4:0' shape=(2,) dtype=int32>

In [20]:
y_data =np.array( [[0, 0, 1],           [0, 0, 1],
          [0, 0, 1],           [0, 1, 0],
          [0, 1, 0],           [0, 1, 0],
          [1, 0, 0],           [1, 0, 0]])


In [22]:
print(y_data.ndim)

2


In [23]:
print(y_data.shape)

(8, 3)


In [27]:
t=np.array([-11,-11])

In [28]:
t

array([-11, -11])

In [29]:
print(t.shape)

(2,)


In [5]:
x = np.array([[[0], [1], [2]]])
x.shape # (1, 3, 1) 

(1, 3, 1)

In [6]:
t=np.squeeze(x)
t

array([0, 1, 2])

In [8]:
x_data=([[1, 2], [3, 4], [5,6]]) 
t=np.squeeze(x_data)
t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
x_data=np.array([[1], [3], [5]]) 
t=np.squeeze(x_data)
t

array([1, 3, 5])

In [15]:
x_data=np.array([[1], [3], [5]]) 
t=tf.squeeze(x_data)
t

<tf.Tensor 'Squeeze_3:0' shape=(3,) dtype=int32>

In [16]:
sess.run(t)

array([1, 3, 5])

In [2]:
mnist.head()

NameError: name 'mnist' is not defined

In [ ]:
import tensorflow as tf
t1 = tf.reduce_mean(1*tf.log(.7)+0)
sess=tf.Session()
t1=sess.run(t1)