# Tensor Manipulation

In [1]:
import tensorflow as tf
x=tf.constant(10, name='x')
y = tf.Variable(x+2, name='y')

model=tf.global_variables_initializer()
with tf.Session() as session:
    session.run(model)
    print(session.run(y))
    

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


12


In [1]:
import tensorflow as tf
import numpy as np  # 

x=tf.constant(10, name='x')
y = tf.Variable(x+2, name='y')

model=tf.global_variables_initializer()
with tf.Session() as session:
    session.run(model)
    print(session.run(y))

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


12


In [1]:
# tensorboard graph
import tensorflow as tf
 
a = tf.add(1, 20, name='a')
b = tf.multiply(a ,3, name='b')
c = tf.div(b, 5,name='c')
e = tf.multiply(b, c,name='e')

with tf.Session() as sess:
   # writer = tf.summary.FileWriter("c:\anaconda\tempo\graph1",sess.graph)
    writer = tf.summary.FileWriter('./graph2',sess.graph)
    print(sess.run(e))
    writer.close()

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


756


In [ ]:
# anaconda open terminal  

# tensorboard --logdir="c:\Users\gwihy\ML_01\graph2" --host 127.0.0.1

In [21]:
# placeholer

a = tf.placeholder("float")
b = tf.placeholder("float")

x = tf.multiply(a, b, name='x')
y = tf.add(x, x, name='y')

with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graph2',sess.graph)
    sess.run(tf.global_variables_initializer())
    print(sess.run(x, feed_dict={a: 2, b: 2}))
    print(sess.run(y, feed_dict={a: 3, b: 3}))
    # print(sess.run(out))

4.0
18.0


In [3]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [4]:
x = tf.constant([[1., 1.], [2., 2.]])
tf.reduce_mean(x)  # 1.5
tf.reduce_mean(x, 0)  # [1.5, 1.5]
tf.reduce_mean(x, 1)  # [1.,  2.]

<tf.Tensor 'Mean_5:0' shape=(2,) dtype=float32>

In [11]:
# Simple Array¶

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [4]:
# 2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [13]:
# Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [14]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [16]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [17]:
# Matmul VS multiply
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [18]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [19]:
# Watch out broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [21]:
# Random values for variable initializations
tf.random_normal([3]).eval()

array([ 0.66267395,  0.04642555, -2.2536268 ], dtype=float32)

In [22]:
tf.random_uniform([2]).eval()

array([0.767277, 0.777598], dtype=float32)

In [23]:
tf.random_uniform([2, 3]).eval()

array([[0.97334003, 0.19341731, 0.15404963],
       [0.7794316 , 0.84300745, 0.02502525]], dtype=float32)

In [24]:
# Reduce Mean/Sum
tf.reduce_mean([1, 2], axis=0).eval()

1

In [25]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [26]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [27]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [28]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [29]:
tf.reduce_sum(x).eval()

10.0

In [30]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [31]:
# 가장 안쪽
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [32]:
# sum 후에 줄여서 평균
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [33]:
# Argmax with axis
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [34]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [35]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

In [ ]:
# Reshape, squeeze, expand_dims
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

In [ ]:
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

In [ ]:
tf.squeeze([[0], [1], [2]]).eval()

In [ ]:
tf.expand_dims([0, 1, 2], 1).eval()

In [ ]:
# One hot
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

In [ ]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
# casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

In [ ]:
# Stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

In [ ]:
tf.stack([x, y, z], axis=1).eval()

In [ ]:
# Ones like and Zeros like
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

In [ ]:
tf.zeros_like(x).eval()

In [ ]:
# Zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

In [ ]:
# Transpose
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

In [ ]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

In [ ]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

In [ ]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))