## 23. tensor manipulation

In [1]:
import tensorflow as tf

In [11]:
sess = tf.InteractiveSession()
mat1 = tf.constant([[1., 2.], [3., 4.]])
mat2 = tf.constant([[10.], [20.]])
x1 = tf.constant([1, 2]) 

print(tf.reduce_mean(x1,axis=0).eval()) 

1


## axis=1 : error

In [13]:
print(tf.reduce_mean(x1,axis=0).eval())

1


In [14]:
print(tf.reduce_mean([1, 2], axis=0 ).eval())

1


In [17]:
print(tf.reduce_mean([[1, 2],[6, 8]],  axis=0 ).eval())

[3 5]


In [18]:
print(tf.reduce_mean([[1, 2],[6, 8]],  axis=1 ).eval())

[1 7]


In [19]:
print(tf.reduce_sum([[1, 2],[6, 8]]).eval())

17


In [21]:
print(tf.reduce_sum([[1, 2],[6, 8]],  axis=1).eval())

[ 3 14]


In [26]:
print(tf.reduce_mean(tf.reduce_sum([[1, 2],[6, 8]],  axis=1)).eval())

8


In [30]:
x1 = tf.constant([[1, 2, 3], [0, 6, 5], [0, 0, 7]]) 
print(tf.argmax(x1, axis=0).eval())

[0 1 2]


In [32]:
print(tf.argmax(x1, axis=1).eval())

[2 1 2]


In [34]:
print(tf.argmax(x1, axis=-1).eval())

[2 1 2]


In [40]:
x1 = tf.constant([[[1, 2, 3], [0, 6, 5]], [[0, 0, 7], [1, 1, 2]]]) 
print(tf.argmax(x1, axis=-1).eval())

[[2 1]
 [2 2]]


In [41]:
# reshape
x1 = tf.constant([[[1, 2, 3], [0, 6, 5]], [[0, 0, 7], [1, 1, 2]]]) 
print(tf.reshape(x1, shape=[-1, 3]).eval())

[[1 2 3]
 [0 6 5]
 [0 0 7]
 [1 1 2]]


In [45]:
print(x1)

Tensor("Const_18:0", shape=(2, 2, 3), dtype=int32)


In [46]:
# reshape(squeeze, expand)
print(tf.squeeze([[1], [2], [3]]).eval())

[1 2 3]


In [47]:
print(tf.expand_dims([0, 1, 2, 3], 1).eval())

[[0]
 [1]
 [2]
 [3]]


In [51]:
# one_hot : rank + 1 
print(tf.one_hot([[0], [1], [2], [3]], depth=4).eval())

[[[1. 0. 0. 0.]]

 [[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]]


In [53]:
t = tf.one_hot([[0], [1], [2], [3]], depth=4).eval()
print(tf.reshape(t, shape=[-1,4]).eval())

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
# casting
print(tf.cast([1.1, 2.2, 3.3, 4.5], tf.int32).eval())
print(tf.cast([True, False, 1 ==1, 0 == 1], tf.int32).eval())

[1 2 3 4]
[1 0 1 0]


In [60]:
# stack
x = [1,2]
y = [2,4]
z = [3, 6]
print(tf.stack([x,y,z]).eval())
print(tf.stack([x,y,z],axis=1).eval())

[[1 2]
 [2 4]
 [3 6]]
[[1 2 3]
 [2 4 6]]


In [63]:
# ones and zeros like
print(tf.ones_like([x,y]).eval())
print(tf.zeros_like([z]).eval())

[[1 1]
 [1 1]]
[[0 0]]


In [64]:
# zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x,y)

1 4
2 5
3 6


## 

In [4]:
# Lab 9 XOR
# This example does not work
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
# @@ -28,7 +29,7 @@
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

SyntaxError: invalid syntax (<ipython-input-4-af406f63e14f>, line 12)

In [5]:
## 9-2 

# Lab 9 XOR-back_prop
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

def sigmoidGradient(z):
  return tf.multiply(tf.sigmoid(z), (1 - tf.sigmoid(z)))

diff = hypothesis - Y

d_l2 = tf.multiply(diff, sigmoidGradient(tf.matmul(layer1, W2) + b2))
d_b2 = d_l2
d_W2 = tf.matmul(tf.transpose(layer1), d_l2)

d_l1 = tf.multiply(tf.matmul(d_l2, tf.transpose(W2)), sigmoidGradient(tf.matmul(X, W1) + b1))
d_b1 = d_l1
d_W1 = tf.matmul(tf.transpose(X), d_l1)

step = [
  tf.assign(W2, W2 - learning_rate * d_W2),
  tf.assign(b2, b2 - learning_rate * tf.reduce_mean(d_b2, axis=[0])),
  tf.assign(W1, W1 - learning_rate * d_W1),
  tf.assign(b1, b1 - learning_rate * tf.reduce_mean(d_b1, axis=[0]))
]

# Accuracy computation
# True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for i in range(10001):
        sess.run([step, cost], feed_dict={X: x_data, Y: y_data})
        if i % 1000 == 0:
            print(i, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.756395 [array([[ 0.79900825,  0.68013245],
       [-1.2195474 , -0.30378452]], dtype=float32), array([[ 1.3762276 ],
       [-0.78775096]], dtype=float32)]
1000 0.69325805 [array([[ 0.528568  ,  0.6371205 ],
       [-1.476141  , -0.00360875]], dtype=float32), array([[ 0.70704406],
       [-0.90937525]], dtype=float32)]
2000 0.6907764 [array([[ 0.67420286,  0.5874193 ],
       [-1.7303791 ,  0.07627835]], dtype=float32), array([[ 0.6553235 ],
       [-0.83637714]], dtype=float32)]
3000 0.68328 [array([[ 1.02093   ,  0.6253037 ],
       [-2.2048264 ,  0.07429429]], dtype=float32), array([[ 0.8740303 ],
       [-0.87200785]], dtype=float32)]
4000 0.64463913 [array([[ 1.8162546 ,  0.83533657],
       [-3.1049178 , -0.13815865]], dtype=float32), array([[ 1.6551832],
       [-1.1272683]], dtype=float32)]
5000 0.5365058 [array([[ 3.0479398,  1.5753363],
       [-4.179672 , -0.8447854]], dtype=float32), array([[ 3.100216 ],
       [-1.9219962]], dtype=float32)]
6000 0.32555458 [array([[ 4.

In [6]:
## 9-2
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
# @@ -29,7 +31,7 @@
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

SyntaxError: invalid syntax (<ipython-input-6-494f54bbdd7e>, line 12)

In [7]:
## 9-3
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
# @@ -37,7 +39,7 @@
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

SyntaxError: invalid syntax (<ipython-input-7-21ac5be723fa>, line 12)

In [8]:
## 9-4
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.01

x_data = [[0, 0],
          [0, 1],
# @@ -43,7 +45,7 @@
    cost_summ = tf.summary.scalar("cost", cost)

with tf.name_scope("train") as scope:
    train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
    train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

SyntaxError: invalid syntax (<ipython-input-8-841e2b06e43c>, line 12)

## 9-2 lab-09-2-xor-nn.py

In [9]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.71451145 [array([[ 0.5328328 ,  0.1915509 ],
       [-0.17282915, -0.35143712]], dtype=float32), array([[ 1.0038856],
       [-1.2314751]], dtype=float32)]
100 0.69294196 [array([[ 0.49955612,  0.23175456],
       [-0.23645274, -0.2871752 ]], dtype=float32), array([[ 0.90110356],
       [-1.3352774 ]], dtype=float32)]
200 0.692718 [array([[ 0.4997566 ,  0.23463312],
       [-0.27265418, -0.26583567]], dtype=float32), array([[ 0.9083011],
       [-1.331628 ]], dtype=float32)]
300 0.69249916 [array([[ 0.5023377 ,  0.23823029],
       [-0.30966318, -0.24930426]], dtype=float32), array([[ 0.91828555],
       [-1.3271018 ]], dtype=float32)]
400 0.692268 [array([[ 0.5072041 ,  0.24297711],
       [-0.34828308, -0.23651886]], dtype=float32), array([[ 0.9295002],
       [-1.3233917]], dtype=float32)]
500 0.692013 [array([[ 0.5147659 ,  0.24874757],
       [-0.38893065, -0.22715805]], dtype=float32), array([[ 0.94211227],
       [-1.3204174 ]], dtype=float32)]
600 0.6917205 [array([[ 0.5254

5500 0.04291935 [array([[ 5.3719397,  5.271513 ],
       [-5.547337 , -4.9986386]], dtype=float32), array([[ 8.075332 ],
       [-7.4924264]], dtype=float32)]
5600 0.041235115 [array([[ 5.3985496,  5.3068094],
       [-5.57419  , -5.034203 ]], dtype=float32), array([[ 8.147362 ],
       [-7.5681076]], dtype=float32)]
5700 0.039671406 [array([[ 5.4240885,  5.340591 ],
       [-5.599993 , -5.0682387]], dtype=float32), array([[ 8.2169895],
       [-7.6411166]], dtype=float32)]
5800 0.038216338 [array([[ 5.4486327,  5.372971 ],
       [-5.624816 , -5.1008596]], dtype=float32), array([[ 8.284357 ],
       [-7.7116246]], dtype=float32)]
5900 0.036859106 [array([[ 5.4722495,  5.4040504],
       [-5.648727 , -5.1321692]], dtype=float32), array([[ 8.349604 ],
       [-7.7797923]], dtype=float32)]
6000 0.0355906 [array([[ 5.4950013,  5.433919 ],
       [-5.6717834, -5.1622596]], dtype=float32), array([[ 8.412849],
       [-7.845764]], dtype=float32)]
6100 0.034402635 [array([[ 5.5169454,  5.4626

## 9-3 lab-09-3-xor-nn-wide-deep.py	

In [10]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 1.017999 [array([[-2.4575992 ,  3.0821822 , -1.1273118 , -1.4135721 , -0.2788174 ,
         0.9084085 ,  0.41095206, -1.0261766 ,  0.4511145 , -0.2794878 ],
       [ 0.55591905, -0.25965255, -0.7949547 , -0.56578696,  0.17938161,
        -0.1422761 ,  0.95862675,  0.88641334,  1.167709  , -1.183361  ]],
      dtype=float32), array([[-1.0516989 , -0.5526261 ,  0.9792131 , -1.8414547 ,  2.3181887 ,
         0.5986555 , -0.39954108,  0.61954   , -0.38777238, -0.1066996 ],
       [-1.1484406 , -0.00588625,  0.6066901 ,  0.7680192 , -0.2607187 ,
         0.26193023, -0.48453942,  1.0957508 , -2.30952   , -0.27126977],
       [-0.6317575 ,  0.62779284,  0.9803063 ,  0.33762807,  0.85427684,
        -0.6062149 , -0.5134146 , -1.8824205 ,  0.7394778 , -1.510983  ],
       [-0.9732664 , -1.1076779 ,  0.44440293,  0.62660104,  0.48785818,
        -0.16217554,  1.3146416 , -0.13543749,  0.82096636,  0.6177628 ],
       [ 0.40085357, -1.0979621 ,  0.8667671 , -0.9624162 , -0.17792983,
        -0

700 0.6836668 [array([[-2.3972325 ,  3.092115  , -1.2541347 , -1.4460119 , -0.2582481 ,
         0.881241  ,  0.40806305, -0.96364135,  0.27159974, -0.03651368],
       [ 0.284574  , -0.19470687, -0.89575374, -0.51430964,  0.21628356,
        -0.1557446 ,  0.9542464 ,  0.7552954 ,  1.2611765 , -1.3551348 ]],
      dtype=float32), array([[-1.0527563 , -0.5569341 ,  1.01245   , -1.8604048 ,  2.3196573 ,
         0.6232874 , -0.37818822,  0.6472935 , -0.3063298 , -0.16807538],
       [-1.1681651 ,  0.02084678,  0.57225305,  0.56284165, -0.2602928 ,
         0.1975163 , -0.5063693 ,  1.0810317 , -2.4183688 , -0.23307134],
       [-0.63197917,  0.6369553 ,  1.0310619 ,  0.19930531,  0.8387297 ,
        -0.60689026, -0.5141706 , -1.9652603 ,  0.74948174, -1.5622991 ],
       [-0.9761705 , -1.0965208 ,  0.5315079 ,  0.49595025,  0.48748344,
        -0.13566694,  1.3065417 , -0.204566  ,  0.8540818 ,  0.61516726],
       [ 0.39931795, -1.09659   ,  0.87255913, -0.9792081 , -0.17682779,
       

      dtype=float32)]
1400 0.65045196 [array([[-2.3955920e+00,  3.1307561e+00, -1.4403594e+00, -1.5062051e+00,
        -2.3732165e-01,  8.4894043e-01,  4.0982181e-01, -9.3688822e-01,
        -1.0515373e-03,  2.9152864e-01],
       [ 1.5924773e-01, -2.9373151e-01, -1.0242718e+00, -5.2034587e-01,
         2.8861439e-01, -1.9434425e-01,  9.4072378e-01,  6.2329835e-01,
         1.5941823e+00, -1.7845010e+00]], dtype=float32), array([[-1.0252215 , -0.56164783,  1.0597162 , -1.9650191 ,  2.3208349 ,
         0.67010784, -0.37027562,  0.6327814 , -0.1545531 , -0.24796687],
       [-1.185098  ,  0.03897408,  0.44828883,  0.6247437 , -0.26074013,
         0.09253968, -0.52493584,  1.0857058 , -2.5945997 , -0.16388644],
       [-0.6087868 ,  0.64215773,  1.0457792 ,  0.14837156,  0.81217885,
        -0.6129485 , -0.51828504, -2.1008618 ,  0.7710661 , -1.6482049 ],
       [-0.9652001 , -1.0967575 ,  0.60171926,  0.39452535,  0.4852914 ,
        -0.10403874,  1.2991427 , -0.2945165 ,  0.91731465, 

2200 0.37285244 [array([[-2.4425113 ,  3.4229798 , -1.7757423 , -1.6137657 , -0.18909036,
         0.8312457 ,  0.38470697, -0.8810927 , -0.6316916 ,  0.9014142 ],
       [ 0.09623931, -0.78473896, -1.4122782 , -0.6911897 ,  0.49976128,
        -0.38225475,  0.951735  ,  0.39564162,  2.4248388 , -2.6621928 ]],
      dtype=float32), array([[-0.7079918 , -0.55560565,  1.208314  , -2.2214856 ,  2.3240378 ,
         0.83766043, -0.38550597,  0.5293    ,  0.07721265, -0.3282892 ],
       [-1.5294082 , -0.01254422,  0.26859853,  0.9940983 , -0.26229814,
        -0.07327087, -0.51579916,  1.1007631 , -3.2939937 , -0.02331773],
       [-0.47318697,  0.6280851 ,  1.1689099 ,  0.06697113,  0.7801082 ,
        -0.53732145, -0.5168884 , -2.477839  ,  0.6327305 , -1.7337537 ],
       [-0.86885375, -1.111265  ,  0.74680424,  0.24574877,  0.48283198,
        -0.01679558,  1.2944036 , -0.5036949 ,  0.9153483 ,  0.58664143],
       [ 0.43534154, -1.0989248 ,  0.89265215, -1.0272609 , -0.16959414,
     

        -1.86639380e+00]], dtype=float32)]
2600 0.14397615 [array([[-2.4773555 ,  3.7227452 , -2.0201485 , -1.6872326 , -0.15408376,
         0.8595002 ,  0.34268224, -0.8498703 , -0.9793971 ,  1.209525  ],
       [ 0.27101234, -1.0369614 , -1.60506   , -0.70927674,  0.6587565 ,
        -0.5380939 ,  0.96943456,  0.3467455 ,  2.8545713 , -3.0425406 ]],
      dtype=float32), array([[-0.50301445, -0.5498241 ,  1.3457401 , -2.3963075 ,  2.3272133 ,
         0.9632969 , -0.39053917,  0.4272398 ,  0.26968062, -0.29069442],
       [-1.8659056 , -0.04623623,  0.1029934 ,  1.1916759 , -0.28404558,
        -0.18116282, -0.5377697 ,  1.1854008 , -3.794124  , -0.0305184 ],
       [-0.43763977,  0.62039334,  1.2611728 , -0.01724556,  0.762937  ,
        -0.46882397, -0.518584  , -2.7337325 ,  0.55090636, -1.7115669 ],
       [-0.82522213, -1.1161168 ,  0.82749003,  0.16336264,  0.47963443,
         0.03841058,  1.291335  , -0.63650477,  0.90788037,  0.611751  ],
       [ 0.45031646, -1.1013308 ,  

      dtype=float32)]
3400 0.035554912 [array([[-2.4833493 ,  3.983419  , -2.2661047 , -1.7615788 , -0.10547591,
         0.8966401 ,  0.30059755, -0.848115  , -1.2195122 ,  1.4121511 ],
       [ 0.60435015, -1.2138839 , -1.7247912 , -0.68085027,  0.82815677,
        -0.68375325,  0.984829  ,  0.37436116,  3.2135022 , -3.3453019 ]],
      dtype=float32), array([[-0.3497546 , -0.54659724,  1.5067956 , -2.5651217 ,  2.3322687 ,
         1.0544719 , -0.38021234,  0.3414022 ,  0.4876557 , -0.25911847],
       [-2.1353865 , -0.0553508 , -0.0555283 ,  1.3545518 , -0.31473246,
        -0.25071722, -0.5721042 ,  1.2990551 , -4.236558  , -0.02433714],
       [-0.41053724,  0.6166973 ,  1.354361  , -0.09606621,  0.74747247,
        -0.41030166, -0.52028495, -2.9616482 ,  0.48656777, -1.6743574 ],
       [-0.7894065 , -1.1175948 ,  0.8980582 ,  0.09767323,  0.47493717,
         0.07937446,  1.2916166 , -0.7474117 ,  0.9160988 ,  0.6347976 ],
       [ 0.45464045, -1.103092  ,  0.95248914, -1.09631

4200 0.016924262 [array([[-2.4814215 ,  4.0859323 , -2.3644354 , -1.7925675 , -0.08320226,
         0.91446656,  0.28177828, -0.8560755 , -1.3117789 ,  1.4835186 ],
       [ 0.7764522 , -1.2767859 , -1.7712471 , -0.6667344 ,  0.9050488 ,
        -0.7468861 ,  0.9912477 ,  0.39416578,  3.3414383 , -3.45346   ]],
      dtype=float32), array([[-2.89169192e-01, -5.47020793e-01,  1.58397698e+00,
        -2.63738728e+00,  2.33555532e+00,  1.08493066e+00,
        -3.72940660e-01,  3.09288710e-01,  5.78631938e-01,
        -2.45148614e-01],
       [-2.24913859e+00, -5.36257327e-02, -1.26019895e-01,
         1.42287230e+00, -3.38130772e-01, -2.75365651e-01,
        -5.83493948e-01,  1.34639680e+00, -4.40788126e+00,
        -1.64578706e-02],
       [-3.99477839e-01,  6.15219533e-01,  1.39489579e+00,
        -1.28530115e-01,  7.40827918e-01, -3.88173223e-01,
        -5.20280004e-01, -3.05563307e+00,  4.59981740e-01,
        -1.65471172e+00],
       [-7.73578584e-01, -1.11809289e+00,  9.26404357e-0

4800 0.011619834 [array([[-2.4808125 ,  4.1319947 , -2.4082215 , -1.8068297 , -0.0727703 ,
         0.92317086,  0.2729749 , -0.8611245 , -1.3531897 ,  1.5148307 ],
       [ 0.859351  , -1.303999  , -1.7932054 , -0.6605992 ,  0.94177556,
        -0.7765881 ,  0.9943165 ,  0.40383124,  3.3957622 , -3.4992979 ]],
      dtype=float32), array([[-0.26127094, -0.5475877 ,  1.6213937 , -2.671178  ,  2.337387  ,
         1.0978822 , -0.3695204 ,  0.29530546,  0.6188218 , -0.2376249 ],
       [-2.3021305 , -0.05188993, -0.1589617 ,  1.454004  , -0.35153896,
        -0.28590193, -0.5888728 ,  1.3677638 , -4.484001  , -0.01214149],
       [-0.39432153,  0.61455333,  1.4137754 , -0.14354974,  0.7376917 ,
        -0.37841102, -0.5203318 , -3.0985715 ,  0.44784558, -1.6449013 ],
       [-0.765772  , -1.1183205 ,  0.93924123,  0.06248193,  0.47064862,
         0.09975812,  1.2943813 , -0.8107249 ,  0.92464715,  0.64906067],
       [ 0.45468086, -1.1040343 ,  0.97808546, -1.120245  , -0.15491249,
    

5300 0.009069514 [array([[-2.4807987 ,  4.1606584 , -2.4352229 , -1.8158003 , -0.06618764,
         0.92883706,  0.26740852, -0.86470205, -1.3789531 ,  1.5341799 ],
       [ 0.91217995, -1.3206164 , -1.8072811 , -0.65689266,  0.96530867,
        -0.7954907 ,  0.9962852 ,  0.4099718 ,  3.4284625 , -3.526823  ]],
      dtype=float32), array([[-0.24372174, -0.5480623 ,  1.6455036 , -2.6925886 ,  2.3386428 ,
         1.10572   , -0.3673924 ,  0.28675196,  0.6434164 , -0.23240787],
       [-2.3357418 , -0.05051617, -0.1797149 ,  1.47346   , -0.3609036 ,
        -0.2922664 , -0.592397  ,  1.3810197 , -4.5310326 , -0.00927543],
       [-0.39107242,  0.6141422 ,  1.4257182 , -0.15303184,  0.73568374,
        -0.37240702, -0.5203914 , -3.1254675 ,  0.4402734 , -1.6384808 ],
       [-0.7606697 , -1.1184512 ,  0.9472566 ,  0.05578308,  0.46963555,
         0.10351417,  1.2950991 , -0.8228933 ,  0.9266034 ,  0.65201175],
       [ 0.45467225, -1.1042131 ,  0.9834653 , -1.125043  , -0.15411739,
    

        -3.8485425e+00, -2.0453465e+00]], dtype=float32)]
6000 0.0068416595 [array([[-2.4812722 ,  4.191859  , -2.4643402 , -1.8256409 , -0.0589677 ,
         0.93524367,  0.26128286, -0.86895156, -1.406988  ,  1.5551709 ],
       [ 0.97047603, -1.3384322 , -1.8229799 , -0.65296865,  0.99150866,
        -0.81642264,  0.99847925,  0.41671827,  3.4630473 , -3.555846  ]],
      dtype=float32), array([[-2.24477917e-01, -5.48673809e-01,  1.67242682e+00,
        -2.71619201e+00,  2.34012842e+00,  1.11405540e+00,
        -3.65097374e-01,  2.77575612e-01,  6.69742644e-01,
        -2.26191297e-01],
       [-2.37291741e+00, -4.87728827e-02, -2.02444285e-01,
         1.49466717e+00, -3.72046381e-01, -2.99024582e-01,
        -5.96440911e-01,  1.39537668e+00, -4.58189774e+00,
        -6.03860477e-03],
       [-3.87510568e-01,  6.13698244e-01,  1.43886673e+00,
        -1.63463026e-01,  7.33444214e-01, -3.65944356e-01,
        -5.20474851e-01, -3.15486217e+00,  4.32042748e-01,
        -1.63121438e+00

        -3.8739569e+00, -2.0506978e+00]], dtype=float32)]
6600 0.005603875 [array([[-2.4819458 ,  4.2131414 , -2.4840102 , -1.8323958 , -0.05402193,
         0.9397674 ,  0.25706962, -0.87204814, -1.4261    ,  1.5694661 ],
       [ 1.0105776 , -1.3504242 , -1.8339163 , -0.6503612 ,  1.0097227 ,
        -0.8309058 ,  1.0000061 ,  0.4213399 ,  3.486019  , -3.5750554 ]],
      dtype=float32), array([[-2.11279079e-01, -5.49152672e-01,  1.69117069e+00,
        -2.73244953e+00,  2.34121585e+00,  1.11962092e+00,
        -3.63552481e-01,  2.71400630e-01,  6.87399268e-01,
        -2.21599773e-01],
       [-2.39864373e+00, -4.74405885e-02, -2.17992648e-01,
         1.50912571e+00, -3.80238712e-01, -3.03534538e-01,
        -5.99350631e-01,  1.40510917e+00, -4.61637878e+00,
        -3.78081040e-03],
       [-3.85070175e-01,  6.13397360e-01,  1.44791245e+00,
        -1.70637831e-01,  7.31882870e-01, -3.61585557e-01,
        -5.20546377e-01, -3.17496204e+00,  4.26450104e-01,
        -1.62609136e+00]

7000 0.0049846014 [array([[-2.482501  ,  4.2253447 , -2.4952104 , -1.8362837 , -0.05118185,
         0.942421  ,  0.25464234, -0.8738907 , -1.4370522 ,  1.5776596 ],
       [ 1.0336561 , -1.3572422 , -1.8402706 , -0.64889216,  1.0202904 ,
        -0.83928216,  1.000892  ,  0.42399287,  3.4989607 , -3.5858479 ]],
      dtype=float32), array([[-2.0368811e-01, -5.4944706e-01,  1.7020483e+00, -2.7418218e+00,
         2.3418834e+00,  1.1227676e+00, -3.6267588e-01,  2.6789206e-01,
         6.9740546e-01, -2.1883059e-01],
       [-2.4135342e+00, -4.6626005e-02, -2.2691280e-01,  1.5174054e+00,
        -3.8515911e-01, -3.0608487e-01, -6.0108346e-01,  1.4106616e+00,
        -4.6360664e+00, -2.4741485e-03],
       [-3.8366818e-01,  6.1322832e-01,  1.4531229e+00, -1.7477126e-01,
         7.3097444e-01, -3.5910606e-01, -5.2059406e-01, -3.1864996e+00,
         4.2325553e-01, -1.6230930e+00],
       [-7.4841440e-01, -1.1187477e+00,  9.6538627e-01,  4.0760357e-02,
         4.6708673e-01,  1.1178425e-0

7600 0.0042605125 [array([[-2.4833694 ,  4.241383  , -2.5098467 , -1.841412  , -0.04744555,
         0.94597965,  0.25143874, -0.8763836 , -1.4514449 ,  1.5884324 ],
       [ 1.0640662 , -1.3661438 , -1.8487178 , -0.6469887 ,  1.0343212 ,
        -0.8503737 ,  1.0020707 ,  0.42748162,  3.515722  , -3.5997894 ]],
      dtype=float32), array([[-1.93683878e-01, -5.49858332e-01,  1.71648669e+00,
        -2.75419664e+00,  2.34275889e+00,  1.12685597e+00,
        -3.61534595e-01,  2.63315260e-01,  7.10425794e-01,
        -2.15031937e-01],
       [-2.43327403e+00, -4.55002710e-02, -2.38638461e-01,
         1.52827442e+00, -3.91881198e-01, -3.09399903e-01,
        -6.03441656e-01,  1.41792881e+00, -4.66185331e+00,
        -7.48158258e-04],
       [-3.81822616e-01,  6.13006115e-01,  1.45999575e+00,
        -1.80225879e-01,  7.29764879e-01, -3.55869114e-01,
        -5.20665586e-01, -3.20167756e+00,  4.19071823e-01,
        -1.61908162e+00],
       [-7.45207012e-01, -1.11881924e+00,  9.69883144e-

        -3.9258482e+00, -2.0613708e+00]], dtype=float32)]
8300 0.0036284819 [array([[-2.4845376 ,  4.2574515 , -2.5243948 , -1.8465651 , -0.04370416,
         0.9496251 ,  0.24821787, -0.87895364, -1.4658455 ,  1.5992256 ],
       [ 1.0945656 , -1.3749875 , -1.8572817 , -0.64511377,  1.0485268 ,
        -0.86156666,  1.0032641 ,  0.43097392,  3.5322177 , -3.6134605 ]],
      dtype=float32), array([[-1.8364167e-01, -5.5029595e-01,  1.7310927e+00, -2.7666392e+00,
         2.3437045e+00,  1.1308938e+00, -3.6040512e-01,  2.5877434e-01,
         7.2330457e-01, -2.1104249e-01],
       [-2.4532287e+00, -4.4312391e-02, -2.5036752e-01,  1.5391303e+00,
        -3.9890519e-01, -3.1267774e-01, -6.0590225e-01,  1.4251636e+00,
        -4.6875634e+00,  9.8415057e-04],
       [-3.7997273e-01,  6.1278713e-01,  1.4669006e+00, -1.8570885e-01,
         7.2853673e-01, -3.5265520e-01, -5.2074903e-01, -3.2168801e+00,
         4.1490456e-01, -1.6149899e+00],
       [-7.4192482e-01, -1.1189027e+00,  9.7438294e

8700 0.003339652 [array([[-2.4852052 ,  4.265614  , -2.5317466 , -1.8491915 , -0.04180308,
         0.9515118 ,  0.24657565, -0.8802869 , -1.4731618 ,  1.6047164 ],
       [ 1.1100807 , -1.3794571 , -1.8616749 , -0.64417255,  1.0558076 ,
        -0.86728925,  1.0038775 ,  0.43274823,  3.5404932 , -3.620302  ]],
      dtype=float32), array([[-1.78527519e-01, -5.50534308e-01,  1.73857224e+00,
        -2.77298355e+00,  2.34418130e+00,  1.13292336e+00,
        -3.59836012e-01,  2.56482482e-01,  7.29789734e-01,
        -2.08941236e-01],
       [-2.46344781e+00, -4.36858311e-02, -2.56322891e-01,
         1.54463577e+00, -4.02589828e-01, -3.14328730e-01,
        -6.07195258e-01,  1.42882466e+00, -4.70059443e+00,
         1.86424900e-03],
       [-3.79031807e-01,  6.12669885e-01,  1.47041786e+00,
        -1.88503399e-01,  7.27905571e-01, -3.51032168e-01,
        -5.20796716e-01, -3.22460794e+00,  4.12795603e-01,
        -1.61287904e+00],
       [-7.40228951e-01, -1.11895037e+00,  9.76668835e-0

        -3.9439394e+00, -2.0650308e+00]], dtype=float32)]
9100 0.003090466 [array([[-2.4858727 ,  4.273172  , -2.5385253 , -1.851627  , -0.04004489,
         0.95327723,  0.24505316, -0.881536  , -1.479929  ,  1.6097999 ],
       [ 1.1244398 , -1.383578  , -1.8657646 , -0.64330834,  1.0625812 ,
        -0.87260395,  1.0044497 ,  0.4343894 ,  3.5480871 , -3.6265628 ]],
      dtype=float32), array([[-1.73789874e-01, -5.50748885e-01,  1.74552488e+00,
        -2.77886748e+00,  2.34465814e+00,  1.13479042e+00,
        -3.59312534e-01,  2.54371762e-01,  7.35753059e-01,
        -2.06952021e-01],
       [-2.47295070e+00, -4.30926532e-02, -2.61828512e-01,
         1.54972255e+00, -4.06068712e-01, -3.15847576e-01,
        -6.08417928e-01,  1.43220079e+00, -4.71262264e+00,
         2.67731468e-03],
       [-3.78160775e-01,  6.12574518e-01,  1.47367668e+00,
        -1.91093475e-01,  7.27319121e-01, -3.49537015e-01,
        -5.20824194e-01, -3.23175979e+00,  4.10850137e-01,
        -1.61090875e+00]

        -3.9519689e+00, -2.0666411e+00]], dtype=float32)]
9500 0.002873479 [array([[-2.4865403 ,  4.2802057 , -2.5448055 , -1.8538947 , -0.03841116,
         0.9549374 ,  0.24363509, -0.88270974, -1.4862186 ,  1.6145297 ],
       [ 1.1377912 , -1.3873963 , -1.8695885 , -0.64251053,  1.0689108 ,
        -0.8775617 ,  1.0049772 ,  0.43591455,  3.555091  , -3.632328  ]],
      dtype=float32), array([[-1.69380590e-01, -5.50963461e-01,  1.75201571e+00,
        -2.78434515e+00,  2.34513497e+00,  1.13651335e+00,
        -3.58828455e-01,  2.52417624e-01,  7.41264760e-01,
        -2.05063164e-01],
       [-2.48182631e+00, -4.25297357e-02, -2.66942054e-01,
         1.55444443e+00, -4.09363449e-01, -3.17252427e-01,
        -6.09580398e-01,  1.43533111e+00, -4.72378778e+00,
         3.43175302e-03],
       [-3.77350867e-01,  6.12479150e-01,  1.47671080e+00,
        -1.93505183e-01,  7.26768315e-01, -3.48152757e-01,
        -5.20848036e-01, -3.23840880e+00,  4.09046650e-01,
        -1.60905874e+00]

        -3.9594395e+00, -2.0681343e+00]], dtype=float32)]
9900 0.002683036 [array([[-2.487208  ,  4.286765  , -2.5506468 , -1.8560158 , -0.03688674,
         0.95650274,  0.24230881, -0.8838159 , -1.4920888 ,  1.6189495 ],
       [ 1.1502562 , -1.3909506 , -1.8731757 , -0.64177054,  1.0748472 ,
        -0.88220507,  1.0054768 ,  0.43733788,  3.5615826 , -3.637661  ]],
      dtype=float32), array([[-1.6526011e-01, -5.5116099e-01,  1.7580991e+00, -2.7894633e+00,
         2.3455315e+00,  1.1381147e+00, -3.5837820e-01,  2.5060034e-01,
         7.4638242e-01, -2.0326479e-01],
       [-2.4901516e+00, -4.1994318e-02, -2.7171144e-01,  1.5588443e+00,
        -4.1249272e-01, -3.1855774e-01, -6.1068630e-01,  1.4382445e+00,
        -4.7341886e+00,  4.1343938e-03],
       [-3.7659475e-01,  6.1238378e-01,  1.4795456e+00, -1.9575986e-01,
         7.2625268e-01, -3.4686518e-01, -5.2087188e-01, -3.2446153e+00,
         4.0736756e-01, -1.6073192e+00],
       [-7.3574924e-01, -1.1190934e+00,  9.8258126e-

## lab-09-4-xor_tensorboard.py

In [11]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.01

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2], name='x-input')
Y = tf.placeholder(tf.float32, [None, 1], name='y-input')

with tf.name_scope("layer1"):
    W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
    b1 = tf.Variable(tf.random_normal([2]), name='bias1')
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

    w1_hist = tf.summary.histogram("weights1", W1)
    b1_hist = tf.summary.histogram("biases1", b1)
    layer1_hist = tf.summary.histogram("layer1", layer1)


with tf.name_scope("layer2"):
    W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
    b2 = tf.Variable(tf.random_normal([1]), name='bias2')
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

    w2_hist = tf.summary.histogram("weights2", W2)
    b2_hist = tf.summary.histogram("biases2", b2)
    hypothesis_hist = tf.summary.histogram("hypothesis", hypothesis)

# cost/loss function
with tf.name_scope("cost"):
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                           tf.log(1 - hypothesis))
    cost_summ = tf.summary.scalar("cost", cost)

with tf.name_scope("train"):
    train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
accuracy_summ = tf.summary.scalar("accuracy", accuracy)

# Launch graph
with tf.Session() as sess:
    # tensorboard --logdir=./logs/xor_logs
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)  # Show the graph

    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        summary, _ = sess.run([merged_summary, train], feed_dict={X: x_data, Y: y_data})
        writer.add_summary(summary, global_step=step)

        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 1.0288997 [array([[-1.06903493e+00,  1.07763335e-04],
       [ 2.95315385e-01, -1.47803533e+00]], dtype=float32), array([[-1.4015952],
       [ 1.1897819]], dtype=float32)]
100 0.68742704 [array([[-0.55590653,  0.16515973],
       [ 0.96133906, -1.7939632 ]], dtype=float32), array([[-2.0687308],
       [ 0.5708883]], dtype=float32)]
200 0.67026436 [array([[-0.9439937,  1.0681918],
       [ 1.2798828, -2.0129824]], dtype=float32), array([[-2.0901322],
       [ 0.5826348]], dtype=float32)]
300 0.6362234 [array([[-1.4500381,  1.9387492],
       [ 1.8823024, -2.9267552]], dtype=float32), array([[-2.1206753 ],
       [ 0.90426093]], dtype=float32)]
400 0.5876643 [array([[-1.982754 ,  2.9521775],
       [ 2.537743 , -4.0793757]], dtype=float32), array([[-2.1821005],
       [ 1.5033021]], dtype=float32)]
500 0.5494846 [array([[-2.3920808,  3.8735788],
       [ 3.067876 , -5.043621 ]], dtype=float32), array([[-2.2177625],
       [ 2.13965  ]], dtype=float32)]
600 0.5265791 [array([[-2.685732

5200 0.47775352 [array([[ -4.311425 ,  11.5710335],
       [  6.2387967, -12.882885 ]], dtype=float32), array([[-1.7653884],
       [ 8.822321 ]], dtype=float32)]
5300 0.47773147 [array([[ -4.3064113,  11.643587 ],
       [  6.252732 , -12.957045 ]], dtype=float32), array([[-1.7560936],
       [ 8.891221 ]], dtype=float32)]
5400 0.4777109 [array([[ -4.301176,  11.715454],
       [  6.266241, -13.030474]], dtype=float32), array([[-1.7468295],
       [ 8.959378 ]], dtype=float32)]
5500 0.4776916 [array([[ -4.2957487,  11.78666  ],
       [  6.2793527, -13.103205 ]], dtype=float32), array([[-1.7375915],
       [ 9.026819 ]], dtype=float32)]
5600 0.4776737 [array([[ -4.2901506,  11.857246 ],
       [  6.292086 , -13.175272 ]], dtype=float32), array([[-1.7283797],
       [ 9.093576 ]], dtype=float32)]
5700 0.4776569 [array([[ -4.2844043,  11.927245 ],
       [  6.304452 , -13.246705 ]], dtype=float32), array([[-1.7191924],
       [ 9.159682 ]], dtype=float32)]
5800 0.47764117 [array([[ -4.2

In [50]:
sess.close()