## numpy

In [1]:
import numpy as np

In [6]:
a = np.array([0,1,2,3,4,5,6])
print(a)

[0 1 2 3 4 5 6]


In [3]:
a[ : -1]

array([0, 1, 2, 3, 4, 5])

In [4]:
a[ : -2]

array([0, 1, 2, 3, 4])

In [6]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [7]:
a[ : -1]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a[:,1]

array([2, 5, 8])

In [10]:
a[1:2]

array([[4, 5, 6]])

In [11]:
a[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[-1]

array([7, 8, 9])

In [13]:
a[-1,:]

array([7, 8, 9])

In [14]:
a[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a[0:2:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0:2 :, 0:2]

array([[1, 2],
       [4, 5]])

In [22]:
y=a[:,[-1]]

In [23]:
y

array([[3],
       [6],
       [9]])

In [31]:
x_data=a[:, 0:-1]

In [25]:
print(x_data.shape, x_data, y, len(x_data))

(3, 2) [[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]] 3


In [26]:
print(a.shape)

(3, 3)


In [9]:
b = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
print(b.shape)

(4, 3)


## tensorflow

In [15]:
import tensorflow as tf

In [22]:
#
b = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
tf.shape(b) 

<tf.Tensor 'Shape_4:0' shape=(3,) dtype=int32>

In [23]:
print(b.shape)

(2, 2, 3)


In [20]:
b = tf.constant([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
print(b.shape)

(4, 3)


## 

In [32]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  22655.951 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [22.293005]
 [18.633902]]
10 Cost:  6.041753 
Prediction:
 [[155.17455]
 [181.64264]
 [181.76219]
 [193.98837]
 [140.6934 ]]
20 Cost:  5.813164 
Prediction:
 [[155.56952]
 [182.1321 ]
 [182.23676]
 [194.50674]
 [141.06909]]
30 Cost:  5.7920403 
Prediction:
 [[155.56291]
 [182.13885]
 [182.23573]
 [194.50717]
 [141.0766 ]]
40 Cost:  5.7710066 
Prediction:
 [[155.55511]
 [182.14413]
 [182.23325]
 [194.50604]
 [141.08298]]
50 Cost:  5.7501135 
Prediction:
 [[155.54735]
 [182.1494 ]
 [182.23079]
 [194.50493]
 [141.08934]]
60 Cost:  5.7293425 
Prediction:
 [[155.53958]
 [182.15462]
 [182.2283 ]
 [194.50377]
 [141.09566]]
70 Cost:  5.7086334 
Prediction:
 [[155.53186]
 [182.15988]
 [182.22586]
 [194.50269]
 [141.10197]]
80 Cost:  5.688061 
Prediction:
 [[155.52414]
 [182.1651 ]
 [182.22343]
 [194.50157]
 [141.10829]]
90 Cost:  5.6675863 
Prediction:
 [[155.51643]
 [182.1703 ]
 [182.22098]
 [194.50044]
 [141.11455]]
100 

820 Cost:  4.4257364 
Prediction:
 [[155.00562]
 [182.51572]
 [182.0583 ]
 [194.43042]
 [141.52766]]
830 Cost:  4.411739 
Prediction:
 [[154.99925]
 [182.51997]
 [182.05624]
 [194.4296 ]
 [141.53273]]
840 Cost:  4.3978662 
Prediction:
 [[154.99294]
 [182.52425]
 [182.05424]
 [194.42877]
 [141.5378 ]]
850 Cost:  4.383973 
Prediction:
 [[154.9866 ]
 [182.52853]
 [182.05223]
 [194.42796]
 [141.54286]]
860 Cost:  4.3701935 
Prediction:
 [[154.9803 ]
 [182.53278]
 [182.0502 ]
 [194.42715]
 [141.54788]]
870 Cost:  4.3565097 
Prediction:
 [[154.97403]
 [182.53702]
 [182.0482 ]
 [194.42635]
 [141.5529 ]]
880 Cost:  4.3428607 
Prediction:
 [[154.96774]
 [182.54124]
 [182.04619]
 [194.42552]
 [141.55789]]
890 Cost:  4.329303 
Prediction:
 [[154.96152]
 [182.54547]
 [182.0442 ]
 [194.42476]
 [141.5629 ]]
900 Cost:  4.315825 
Prediction:
 [[154.95529]
 [182.54967]
 [182.04219]
 [194.42393]
 [141.56789]]
910 Cost:  4.3023806 
Prediction:
 [[154.94907]
 [182.55388]
 [182.0402 ]
 [194.42314]
 [141.57

1640 Cost:  3.4848378 
Prediction:
 [[154.5361 ]
 [182.83226]
 [181.90764]
 [194.37398]
 [141.89879]]
1650 Cost:  3.4755654 
Prediction:
 [[154.53096]
 [182.83572]
 [181.90598]
 [194.37341]
 [141.90279]]
1660 Cost:  3.4663835 
Prediction:
 [[154.52583]
 [182.83914]
 [181.90433]
 [194.37285]
 [141.90677]]
1670 Cost:  3.4572175 
Prediction:
 [[154.52074]
 [182.8426 ]
 [181.9027 ]
 [194.3723 ]
 [141.91075]]
1680 Cost:  3.4480853 
Prediction:
 [[154.51562]
 [182.84602]
 [181.90103]
 [194.37173]
 [141.9147 ]]
1690 Cost:  3.439036 
Prediction:
 [[154.51056]
 [182.84944]
 [181.8994 ]
 [194.37119]
 [141.91866]]
1700 Cost:  3.4300094 
Prediction:
 [[154.5055 ]
 [182.85284]
 [181.89775]
 [194.37064]
 [141.9226 ]]
1710 Cost:  3.420967 
Prediction:
 [[154.50041]
 [182.85628]
 [181.89612]
 [194.3701 ]
 [141.92654]]
1720 Cost:  3.4120548 
Prediction:
 [[154.49538]
 [182.85965]
 [181.89449]
 [194.36955]
 [141.93047]]
1730 Cost:  3.403165 
Prediction:
 [[154.49036]
 [182.86307]
 [181.8929 ]
 [194.3690

In [33]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  8013.899 
Prediction:
 [[74.180595]
 [80.63322 ]
 [83.980225]
 [91.3227  ]
 [59.210712]
 [41.890907]
 [70.11859 ]
 [54.823997]
 [72.922676]
 [66.100105]
 [65.148254]
 [60.243664]
 [86.905014]
 [71.78623 ]
 [69.10599 ]
 [82.41498 ]
 [65.882515]
 [86.28957 ]
 [84.18406 ]
 [76.09278 ]
 [81.279625]
 [75.88126 ]
 [78.24949 

260 Cost:  22.132778 
Prediction:
 [[157.68208]
 [181.90852]
 [183.28148]
 [199.66252]
 [136.5174 ]
 [ 99.29077]
 [151.24538]
 [114.9823 ]
 [168.01971]
 [154.6918 ]
 [143.38385]
 [137.86307]
 [189.31557]
 [156.70499]
 [150.7636 ]
 [185.28514]
 [146.80573]
 [183.55974]
 [181.64638]
 [163.23439]
 [176.47621]
 [171.021  ]
 [168.87938]
 [158.85593]
 [189.83562]]
270 Cost:  21.996405 
Prediction:
 [[157.66273]
 [181.91853]
 [183.27364]
 [199.66095]
 [136.52754]
 [ 99.3129 ]
 [151.24522]
 [114.98265]
 [168.0453 ]
 [154.7339 ]
 [143.38647]
 [137.883  ]
 [189.30092]
 [156.68509]
 [150.7692 ]
 [185.29887]
 [146.78865]
 [183.55626]
 [181.62617]
 [163.21397]
 [176.47832]
 [171.03506]
 [168.8766 ]
 [158.82101]
 [189.83751]]
280 Cost:  21.861229 
Prediction:
 [[157.64348]
 [181.92851]
 [183.26584]
 [199.65938]
 [136.53767]
 [ 99.33494]
 [151.24507]
 [114.98297]
 [168.0708 ]
 [154.7758 ]
 [143.38908]
 [137.90285]
 [189.28633]
 [156.6653 ]
 [150.77477]
 [185.31256]
 [146.77167]
 [183.55278]
 [181.606

570 Cost:  18.407333 
Prediction:
 [[157.1184  ]
 [182.20201 ]
 [183.05377 ]
 [199.61606 ]
 [136.81622 ]
 [ 99.935326]
 [151.23764 ]
 [114.98572 ]
 [168.76535 ]
 [155.91458 ]
 [143.45894 ]
 [138.44276 ]
 [188.89145 ]
 [156.12997 ]
 [150.92316 ]
 [185.6852  ]
 [146.31491 ]
 [183.45267 ]
 [181.0605  ]
 [162.64159 ]
 [176.53491 ]
 [171.4307  ]
 [168.79562 ]
 [157.8427  ]
 [189.89268 ]]
580 Cost:  18.302938 
Prediction:
 [[157.1014 ]
 [182.2109 ]
 [183.04694]
 [199.61462]
 [136.82533]
 [ 99.95474]
 [151.2373 ]
 [114.98558]
 [168.78784]
 [155.95134]
 [143.46117]
 [138.4602 ]
 [188.87875]
 [156.11281]
 [150.92786]
 [185.69727]
 [146.30035]
 [183.44925]
 [181.04292]
 [162.62378]
 [176.53656]
 [171.44302]
 [168.793  ]
 [157.81227]
 [189.89447]]
590 Cost:  18.19944 
Prediction:
 [[157.08447]
 [182.21979]
 [183.04013]
 [199.6132 ]
 [136.83441]
 [ 99.9741 ]
 [151.23694]
 [114.98544]
 [168.81021]
 [155.98793]
 [143.46338]
 [138.47758]
 [188.86612]
 [156.0957 ]
 [150.93253]
 [185.70926]
 [146.28586

830 Cost:  15.964003 
Prediction:
 [[156.69856]
 [182.42296]
 [182.88551]
 [199.58043]
 [137.0432 ]
 [100.41507]
 [151.22678]
 [114.97832]
 [169.32045]
 [156.81982]
 [143.51317]
 [138.87296]
 [188.57951]
 [155.7087 ]
 [151.03694]
 [185.98297]
 [145.95973]
 [183.36467]
 [180.62791]
 [162.20274]
 [176.57382]
 [171.73547]
 [168.72919]
 [157.094  ]
 [189.93842]]
840 Cost:  15.880471 
Prediction:
 [[156.6833  ]
 [182.43103 ]
 [182.87941 ]
 [199.5791  ]
 [137.05153 ]
 [100.43251 ]
 [151.22627 ]
 [114.977875]
 [169.34062 ]
 [156.85262 ]
 [143.5151  ]
 [138.88857 ]
 [188.56825 ]
 [155.6935  ]
 [151.04099 ]
 [185.99379 ]
 [145.947   ]
 [183.36131 ]
 [180.61226 ]
 [162.18684 ]
 [176.57515 ]
 [171.74654 ]
 [168.7267  ]
 [157.06688 ]
 [189.94014 ]]
850 Cost:  15.797646 
Prediction:
 [[156.6681  ]
 [182.43907 ]
 [182.87334 ]
 [199.5778  ]
 [137.05983 ]
 [100.449875]
 [151.22578 ]
 [114.97742 ]
 [169.3607  ]
 [156.8853  ]
 [143.51704 ]
 [138.90411 ]
 [188.55702 ]
 [155.67839 ]
 [151.045   ]
 [186.00

1100 Cost:  13.941669 
Prediction:
 [[156.30789]
 [182.63065]
 [182.73007]
 [199.54633]
 [137.25833]
 [100.8612 ]
 [151.21207]
 [114.96252]
 [169.83667]
 [157.65717]
 [143.5621 ]
 [139.2718 ]
 [188.29277]
 [155.3229 ]
 [151.13826]
 [186.25986]
 [145.63852]
 [183.27539]
 [180.22879]
 [161.79678]
 [176.60576]
 [172.01872]
 [168.66373]
 [156.40268]
 [189.98386]]
1110 Cost:  13.875332 
Prediction:
 [[156.29425]
 [182.63795]
 [182.72469]
 [199.54512]
 [137.26593]
 [100.87679]
 [151.21146]
 [114.96181]
 [169.85472]
 [157.68633]
 [143.56377]
 [139.2857 ]
 [188.28282]
 [155.30956]
 [151.14171]
 [186.26955]
 [145.62746]
 [183.27213]
 [180.2149 ]
 [161.78265]
 [176.6068 ]
 [172.02863]
 [168.66136]
 [156.37862]
 [189.98552]]
1120 Cost:  13.809601 
Prediction:
 [[156.28065]
 [182.6452 ]
 [182.71928]
 [199.5439 ]
 [137.27348]
 [100.8923 ]
 [151.21083]
 [114.96106]
 [169.87267]
 [157.71536]
 [143.56544]
 [139.29956]
 [188.2729 ]
 [155.29626]
 [151.14514]
 [186.27916]
 [145.61647]
 [183.26888]
 [180.

1360 Cost:  12.388683 
Prediction:
 [[155.97073]
 [182.81177]
 [182.59702]
 [199.51605]
 [137.44754]
 [101.24601]
 [151.19525]
 [114.94093]
 [170.28201]
 [158.37544]
 [143.60297]
 [139.61476]
 [188.04846]
 [154.99556]
 [151.22165]
 [186.49869]
 [145.36958]
 [183.19174]
 [179.88734]
 [161.44858]
 [176.62949]
 [172.26291]
 [168.60397]
 [155.81082]
 [190.0257 ]]
1370 Cost:  12.335513 
Prediction:
 [[155.95847 ]
 [182.81839 ]
 [182.59218 ]
 [199.51492 ]
 [137.4545  ]
 [101.259995]
 [151.19455 ]
 [114.93999 ]
 [170.29819 ]
 [158.40147 ]
 [143.60442 ]
 [139.6272  ]
 [188.03964 ]
 [154.98375 ]
 [151.22458 ]
 [186.50737 ]
 [145.35995 ]
 [183.18857 ]
 [179.87497 ]
 [161.43596 ]
 [176.63028 ]
 [172.27179 ]
 [168.60173 ]
 [155.78937 ]
 [190.02725 ]]
1380 Cost:  12.282821 
Prediction:
 [[155.94626 ]
 [182.82501 ]
 [182.58739 ]
 [199.51382 ]
 [137.46143 ]
 [101.273926]
 [151.19388 ]
 [114.93905 ]
 [170.31432 ]
 [158.4274  ]
 [143.60587 ]
 [139.63962 ]
 [188.03085 ]
 [154.97202 ]
 [151.22754 ]
 [186

1730 Cost:  10.693984 
Prediction:
 [[155.54906 ]
 [183.04121 ]
 [182.43217 ]
 [199.47694 ]
 [137.68959 ]
 [101.72689 ]
 [151.16794 ]
 [114.901726]
 [170.83861 ]
 [159.26697 ]
 [143.652   ]
 [140.04173 ]
 [187.74776 ]
 [154.5947  ]
 [151.3197  ]
 [186.79716 ]
 [145.04597 ]
 [183.07698 ]
 [179.46497 ]
 [161.01637 ]
 [176.65327 ]
 [172.56786 ]
 [168.52426 ]
 [155.07793 ]
 [190.082   ]]
1740 Cost:  10.655126 
Prediction:
 [[155.53853 ]
 [183.04698 ]
 [182.42809 ]
 [199.47594 ]
 [137.69572 ]
 [101.738884]
 [151.16716 ]
 [114.90054 ]
 [170.85251 ]
 [159.28912 ]
 [143.65317 ]
 [140.05237 ]
 [187.74031 ]
 [154.58482 ]
 [151.32204 ]
 [186.80461 ]
 [145.0381  ]
 [183.07396 ]
 [179.45448 ]
 [161.00563 ]
 [176.65378 ]
 [172.57549 ]
 [168.5222  ]
 [155.05974 ]
 [190.08345 ]]
1750 Cost:  10.61663 
Prediction:
 [[155.52803]
 [183.0527 ]
 [182.424  ]
 [199.47493]
 [137.70181]
 [101.75083]
 [151.16635]
 [114.89936]
 [170.86633]
 [159.31117]
 [143.65434]
 [140.06293]
 [187.7329 ]
 [154.57498]
 [151.324

1990 Cost:  9.783297 
Prediction:
 [[155.28874 ]
 [183.1847  ]
 [182.33147 ]
 [199.45193 ]
 [137.84253 ]
 [102.023476]
 [151.14697 ]
 [114.86956 ]
 [171.18196 ]
 [159.81288 ]
 [143.68088 ]
 [140.30402 ]
 [187.56525 ]
 [154.35281 ]
 [151.37616 ]
 [186.98125 ]
 [144.8545  ]
 [182.99954 ]
 [179.20724 ]
 [160.75171 ]
 [176.66412 ]
 [172.7558  ]
 [168.4718  ]
 [154.63028 ]
 [190.11932 ]]
2000 Cost:  9.752089 
Prediction:
 [[155.27927 ]
 [183.18994 ]
 [182.32782 ]
 [199.45102 ]
 [137.84814 ]
 [102.034256]
 [151.14615 ]
 [114.868256]
 [171.19446 ]
 [159.83267 ]
 [143.68192 ]
 [140.31354 ]
 [187.55865 ]
 [154.3441  ]
 [151.37814 ]
 [186.98795 ]
 [144.84769 ]
 [182.99661 ]
 [179.19792 ]
 [160.74213 ]
 [176.66447 ]
 [172.76263 ]
 [168.46985 ]
 [154.61407 ]
 [190.12073 ]]
Your score will be  [[175.88304]]
Other scores will be  [[177.93076]
 [180.93259]]


In [35]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  9467.248 
Prediction:
 [[55.477287]
 [72.04147 ]
 [68.12117 ]
 [75.020905]
 [55.657764]
 [43.077972]
 [55.99079 ]
 [41.08771 ]
 [69.65787 ]
 [66.92915 ]]
10 Cost:  9.26292 
Prediction:
 [[150.7759 ]
 [186.58652]
 [180.98137]
 [197.9386 ]
 [143.01463]
 [107.48995]
 [148.00414]
 [109.30782]
 [176.71484]
 [166.10005]]
20 Cost:  10.789653 
Prediction:
 [[151.42488]
 [187.35318]
 [181.74359]
 [198.76936]
 [143.59549]
 [107.9176 ]
 [148.63065]
 [109.77924]
 [177.42902]
 [166.76173]]
30 Cost:  10.767769 
Prediction:
 [[151.43513 ]
 [187.35207 ]
 [181.74939 ]
 [198.77626 ]
 [143.5908  ]
 [107.913506]
 [148.64049 ]
 [109.79345 ]
 [177.42558 ]
 [166.75868 ]]
40 Cost:  10.732614 
Prediction:
 [[151.44107]
 [187.34578]
 [181.75006]
 [198.77759]
 [143.58218]
 [107.9065 ]
 [148.64615]
 [109.80456]
 [177.41733]
 [166.75117]]
50 Cost:  10.697638 
Prediction:
 [[151.44696]
 [187.3395 ]
 [181.7507 ]
 [198.7789 ]
 [143.57358]
 [107.89951]
 [148.65178]
 [109.81562]
 [177.4091 ]
 [166.74368]]
60 C

520 Cost:  9.255751 
Prediction:
 [[151.70363]
 [187.06271]
 [181.7773 ]
 [198.83655]
 [143.19318]
 [107.5948 ]
 [148.9018 ]
 [110.30754]
 [177.04965]
 [166.4218 ]]
530 Cost:  9.229025 
Prediction:
 [[151.7087 ]
 [187.0572 ]
 [181.7778 ]
 [198.8377 ]
 [143.1856 ]
 [107.5888 ]
 [148.90683]
 [110.31743]
 [177.04259]
 [166.41556]]
540 Cost:  9.202426 
Prediction:
 [[151.71375]
 [187.05171]
 [181.77829]
 [198.83887]
 [143.17802]
 [107.58281]
 [148.91185]
 [110.3273 ]
 [177.03552]
 [166.40935]]
550 Cost:  9.176008 
Prediction:
 [[151.71878]
 [187.04625]
 [181.7788 ]
 [198.84004]
 [143.17049]
 [107.57685]
 [148.91685]
 [110.33716]
 [177.02849]
 [166.40315]]
560 Cost:  9.149726 
Prediction:
 [[151.72379 ]
 [187.0408  ]
 [181.7793  ]
 [198.84119 ]
 [143.16296 ]
 [107.57091 ]
 [148.92186 ]
 [110.346985]
 [177.02147 ]
 [166.39699 ]]
570 Cost:  9.123559 
Prediction:
 [[151.72879]
 [187.03535]
 [181.77977]
 [198.84232]
 [143.15544]
 [107.56498]
 [148.92683]
 [110.35679]
 [177.01447]
 [166.39085]]


1010 Cost:  8.106852 
Prediction:
 [[151.93427 ]
 [186.81042 ]
 [181.79916 ]
 [198.89038 ]
 [142.84425 ]
 [107.3218  ]
 [149.13522 ]
 [110.766304]
 [176.72765 ]
 [166.14246 ]]
1020 Cost:  8.086504 
Prediction:
 [[151.9386 ]
 [186.80562]
 [181.79956]
 [198.8914 ]
 [142.8376 ]
 [107.31664]
 [149.13972]
 [110.77513]
 [176.72157]
 [166.13728]]
1030 Cost:  8.066315 
Prediction:
 [[151.94296 ]
 [186.80084 ]
 [181.79996 ]
 [198.89246 ]
 [142.83095 ]
 [107.311516]
 [149.1442  ]
 [110.783936]
 [176.71553 ]
 [166.13213 ]]
1040 Cost:  8.046199 
Prediction:
 [[151.94728 ]
 [186.79607 ]
 [181.80034 ]
 [198.89348 ]
 [142.82433 ]
 [107.306404]
 [149.14867 ]
 [110.792725]
 [176.70949 ]
 [166.12698 ]]
1050 Cost:  8.026212 
Prediction:
 [[151.9516 ]
 [186.7913 ]
 [181.80072]
 [198.89452]
 [142.81772]
 [107.30131]
 [149.15314]
 [110.80149]
 [176.70348]
 [166.12186]]
1060 Cost:  8.006297 
Prediction:
 [[151.95589 ]
 [186.78654 ]
 [181.8011  ]
 [198.89552 ]
 [142.81114 ]
 [107.29621 ]
 [149.1576  ]
 [110.8

1520 Cost:  7.201781 
Prediction:
 [[152.14026]
 [186.58182]
 [181.81688]
 [198.94025]
 [142.52615]
 [107.07859]
 [149.35156]
 [111.19107]
 [176.4408 ]
 [165.90167]]
1530 Cost:  7.1864944 
Prediction:
 [[152.144   ]
 [186.57765 ]
 [181.81718 ]
 [198.94118 ]
 [142.52034 ]
 [107.074196]
 [149.35555 ]
 [111.1989  ]
 [176.43562 ]
 [165.8974  ]]
1540 Cost:  7.1712503 
Prediction:
 [[152.1477 ]
 [186.5735 ]
 [181.81749]
 [198.94208]
 [142.51453]
 [107.06981]
 [149.35953]
 [111.20672]
 [176.43045]
 [165.89313]]
1550 Cost:  7.1561446 
Prediction:
 [[152.15141 ]
 [186.56935 ]
 [181.8178  ]
 [198.94301 ]
 [142.50874 ]
 [107.065445]
 [149.36351 ]
 [111.21451 ]
 [176.42531 ]
 [165.8889  ]]
1560 Cost:  7.1410766 
Prediction:
 [[152.15512]
 [186.56522]
 [181.81808]
 [198.94391]
 [142.50298]
 [107.06109]
 [149.36746]
 [111.22229]
 [176.42017]
 [165.88467]]
1570 Cost:  7.1261168 
Prediction:
 [[152.1588 ]
 [186.56108]
 [181.81839]
 [198.94484]
 [142.49721]
 [107.05675]
 [149.37141]
 [111.23004]
 [176.

Other scores will be  [[174.82126]
 [175.12984]]


## simple_linear_reg.csv

## simple linear regression result below
 Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[3]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[5], [6]]}))
[2.2685292]
 [1.455509 ]
 [2.2685292]
 [1.455509 ]]
Your score will be  [[3.0815487]]
Other scores will be  [[4.707592 ]
 [5.5206137]]

In [ ]:
# simple linear regression 

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility
 
xy = np.loadtxt('simple_linear_reg.csv', delimiter=',', dtype=np.float32)
# x_data = advertising
# y_data = revenue
x_data = xy[:, [-1]]
y_data = xy[:, 0:-1]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 1])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([1, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-2)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[3]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[5], [6]]}))

In [51]:
import os
os.getcwd()

'C:\\Users\\beomc\\working'

In [ ]:
os.getcwd()

## reduce_mean(tf.cast 

In [52]:
import tensorflow as tf

x = tf.constant([[1., 3.], [2., 6.]])

sess = tf.Session()

print(sess.run(x))
print(sess.run(tf.reduce_mean(x)))
print(sess.run(tf.reduce_mean(x, 0)))
print(sess.run(tf.reduce_mean(x, 1)))

sess.close()

[[1. 3.]
 [2. 6.]]
3.0
[1.5 4.5]
[2. 4.]


## tf.cast

In [54]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [58]:
x = tf.constant([1.91, 2.1], dtype=tf.float64)
print(sess.run(x))
x=tf.cast(x, tf.int32)
print(sess.run(x)) 

[1.91 2.1 ]
[1 2]


In [59]:
# Lab 5 Logistic Regression Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2],  [2, 3],  [3, 1], [4, 3],   [5, 3],    [6, 2]]
y_data = [[0],   [0],   [0],  [1],   [1],    [1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 4.6971893
200 0.55227536
400 0.47473076
600 0.43565997
800 0.41115186
1000 0.39300713
1200 0.37805608
1400 0.36493352
1600 0.35299742
1800 0.3419226
2000 0.33153173
2200 0.32172057
2400 0.31242213
2600 0.30358955
2800 0.29518703
3000 0.2871851
3200 0.2795584
3400 0.27228442
3600 0.26534235
3800 0.25871304
4000 0.25237864
4200 0.24632233
4400 0.24052857
4600 0.23498249
4800 0.22967039
5000 0.22457923
5200 0.21969695
5400 0.21501201
5600 0.21051385
5800 0.20619248
6000 0.20203824
6200 0.19804268
6400 0.19419722
6600 0.19049425
6800 0.18692647
7000 0.18348695
7200 0.18016936
7400 0.17696778
7600 0.17387636
7800 0.17088978
8000 0.16800314
8200 0.1652116
8400 0.16251089
8600 0.15989669
8800 0.15736501
9000 0.15491225
9200 0.15253484
9400 0.15022944
9600 0.14799295
9800 0.14582236
10000 0.14371498

Hypothesis:  [[0.02834667]
 [0.15547107]
 [0.29320008]
 [0.78676337]
 [0.9429157 ]
 [0.98129576]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


## Softmax

In [1]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 5.048624
200 0.5484252
400 0.43214852
600 0.3524663
800 0.2768294
1000 0.23268294
1200 0.21055308
1400 0.19221492
1600 0.17675184
1800 0.16353412
2000 0.15210836
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]] [1]
--------------
[[0.93119204 0.06290206 0.00590588]] [0]
--------------
[[1.2732767e-08 3.3411323e-04 9.9966586e-01]] [2]
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]
 [9.3119204e-01 6.2902056e-02 5.9058843e-03]
 [1.2732767e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
