In [1]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(123)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

In [2]:
## Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
import numpy as np

tf.set_random_seed(123)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of cvs in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

350 Cost:  15.024577 
Prediction:
 [[154.72159]
 [182.69055]
 [181.4886 ]
 [200.20892]
 [136.39995]
 [104.10129]
 [154.5657 ]
 [121.26102]
 [173.08945]
 [165.66374]]
360 Cost:  14.974521 
Prediction:
 [[154.72015]
 [182.69547]
 [181.49036]
 [200.20676]
 [136.40869]
 [104.1022 ]
 [154.55615]
 [121.24264]
 [173.09058]
 [165.65634]]
370 Cost:  14.924696 
Prediction:
 [[154.71875]
 [182.70036]
 [181.49213]
 [200.20459]
 [136.41743]
 [104.10312]
 [154.54662]
 [121.22431]
 [173.09172]
 [165.64897]]
380 Cost:  14.87515 
Prediction:
 [[154.71732]
 [182.70526]
 [181.49387]
 [200.20244]
 [136.42615]
 [104.10405]
 [154.53711]
 [121.20604]
 [173.09285]
 [165.64166]]
390 Cost:  14.825842 
Prediction:
 [[154.71587]
 [182.71013]
 [181.4956 ]
 [200.2003 ]
 [136.43483]
 [104.10498]
 [154.52763]
 [121.1878 ]
 [173.09401]
 [165.63438]]
400 Cost:  14.776744 
Prediction:
 [[154.71442]
 [182.71501]
 [181.49734]
 [200.19815]
 [136.44351]
 [104.10593]
 [154.51817]
 [121.16962]
 [173.09517]
 [165.62714]]
410 C

900 Cost:  12.610529 
Prediction:
 [[154.6375  ]
 [182.94868 ]
 [181.57475 ]
 [200.09831 ]
 [136.85445 ]
 [104.162025]
 [154.07729 ]
 [120.32143 ]
 [173.16371 ]
 [165.31206 ]]
910 Cost:  12.572481 
Prediction:
 [[154.63588 ]
 [182.95316 ]
 [181.57616 ]
 [200.09645 ]
 [136.86223 ]
 [104.163315]
 [154.06909 ]
 [120.30563 ]
 [173.16527 ]
 [165.30663 ]]
920 Cost:  12.534556 
Prediction:
 [[154.63426]
 [182.95763]
 [181.57753]
 [200.09459]
 [136.87   ]
 [104.1646 ]
 [154.0609 ]
 [120.28987]
 [173.16682]
 [165.3012 ]]
930 Cost:  12.496879 
Prediction:
 [[154.63266 ]
 [182.96208 ]
 [181.5789  ]
 [200.09276 ]
 [136.87775 ]
 [104.16588 ]
 [154.05275 ]
 [120.274155]
 [173.1684  ]
 [165.29582 ]]
940 Cost:  12.459356 
Prediction:
 [[154.63104 ]
 [182.96654 ]
 [181.58028 ]
 [200.0909  ]
 [136.88547 ]
 [104.16718 ]
 [154.0446  ]
 [120.258484]
 [173.16997 ]
 [165.29048 ]]
950 Cost:  12.421994 
Prediction:
 [[154.62941]
 [182.971  ]
 [181.58163]
 [200.08907]
 [136.89319]
 [104.16847]
 [154.03648]
 [12

1390 Cost:  10.9471855 
Prediction:
 [[154.55624 ]
 [183.15894 ]
 [181.63586 ]
 [200.01291 ]
 [137.21643 ]
 [104.229744]
 [153.7004  ]
 [119.59551 ]
 [173.24562 ]
 [165.07907 ]]
1400 Cost:  10.917242 
Prediction:
 [[154.55457]
 [183.16302]
 [181.637  ]
 [200.01129]
 [137.22342]
 [104.23123]
 [153.69322]
 [119.58168]
 [173.24739]
 [165.07498]]
1410 Cost:  10.8874 
Prediction:
 [[154.55287 ]
 [183.16711 ]
 [181.63809 ]
 [200.00967 ]
 [137.2304  ]
 [104.2327  ]
 [153.68607 ]
 [119.567894]
 [173.24918 ]
 [165.07089 ]]
1420 Cost:  10.857712 
Prediction:
 [[154.55118]
 [183.1712 ]
 [181.6392 ]
 [200.00806]
 [137.23735]
 [104.23418]
 [153.67892]
 [119.55414]
 [173.25095]
 [165.06685]]
1430 Cost:  10.8281765 
Prediction:
 [[154.54948]
 [183.1753 ]
 [181.64032]
 [200.00645]
 [137.24431]
 [104.23567]
 [153.67181]
 [119.54043]
 [173.25275]
 [165.06284]]
1440 Cost:  10.798725 
Prediction:
 [[154.54778 ]
 [183.17935 ]
 [181.64139 ]
 [200.00482 ]
 [137.25122 ]
 [104.237144]
 [153.6647  ]
 [119.52674

1900 Cost:  9.588292 
Prediction:
 [[154.46939]
 [183.35867]
 [181.68703]
 [199.9354 ]
 [137.55403]
 [104.30792]
 [153.35825]
 [118.93582]
 [173.33968]
 [164.89835]]
1910 Cost:  9.564817 
Prediction:
 [[154.46768 ]
 [183.36241 ]
 [181.68791 ]
 [199.93398 ]
 [137.56027 ]
 [104.3095  ]
 [153.35199 ]
 [118.923775]
 [173.34157 ]
 [164.89532 ]]
1920 Cost:  9.541468 
Prediction:
 [[154.46597]
 [183.36612]
 [181.6888 ]
 [199.93257]
 [137.5665 ]
 [104.31107]
 [153.34576]
 [118.91175]
 [173.34348]
 [164.89233]]
1930 Cost:  9.5182295 
Prediction:
 [[154.46428 ]
 [183.36984 ]
 [181.68968 ]
 [199.93117 ]
 [137.57272 ]
 [104.31266 ]
 [153.33955 ]
 [118.899765]
 [173.34538 ]
 [164.88936 ]]
1940 Cost:  9.495089 
Prediction:
 [[154.46257]
 [183.37355]
 [181.69057]
 [199.92975]
 [137.57893]
 [104.31425]
 [153.33336]
 [118.88782]
 [173.34727]
 [164.88638]]
1950 Cost:  9.472078 
Prediction:
 [[154.46086 ]
 [183.37724 ]
 [181.69145 ]
 [199.92833 ]
 [137.58511 ]
 [104.315834]
 [153.32718 ]
 [118.87591 ]
 [

In [3]:
print("filename_queue")   

filename_queue


In [5]:
filename_queue[0:10]

TypeError: 'FIFOQueue' object is not subscriptable

In [6]:
v1='korea'
print(v1)

korea


In [7]:
v2=[0,1,2,3,4,5]

In [8]:
v2

[0, 1, 2, 3, 4, 5]

In [9]:
v2[1]

1

In [10]:
print(v2)

[0, 1, 2, 3, 4, 5]


In [17]:
# create file
test_file = open('test.txt','w')

In [18]:
test_file.write('hello world')

11

In [19]:
test_file.flush
test_file.close

<function TextIOWrapper.close()>

In [13]:
import os
print (os.getcwd()) #현재 디렉토리의
print (os.path.realpath(__file__))#파일
print (os.path.dirname(os.path.realpath(____file__)) )#파일이 위치한 디렉토리

c:\Users\beomc\working


NameError: name '__file__' is not defined

In [14]:
import os
print (os.getcwd())

c:\Users\beomc\working
