In [1]:
import numpy as np

In [12]:
data1 = [1,2,3]
data1

[1, 2, 3]

### numpy를 이용 array 정의하기 

In [14]:
array1 = np.array(data1) 
array1

array([1, 2, 3])

In [15]:
array1.shape

(3,)

In [18]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
array2.shape

(4, 3)

In [20]:
array3 = np.array([[1,1,1],[2,2,2],[3,3,3],[4, 4, 4]])

In [21]:
array2 + array3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [22]:
array2 - array3

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [23]:
array1 = np.array([[1,1,1],[2,2,2]])

In [27]:
array2 = np.array([1,2,3])

In [28]:
array1 * array2

array([[1, 2, 3],
       [2, 4, 6]])

## matrix multiply

In [32]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1[3]

3

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [36]:
names = np.array(['Beom','Beom','Kim','Joa','Lee','Beom','Park','Kim'])
names 

array(['Beom', 'Beom', 'Kim', 'Joa', 'Lee', 'Beom', 'Park', 'Kim'],
      dtype='<U4')

In [45]:
data = np.random.randn(8,3)
data

array([[-0.39331188,  0.4949925 ,  1.21950139],
       [ 0.2372299 ,  0.18230849, -0.07196792],
       [-1.36293573,  1.13901194,  0.40286579],
       [-0.54079192,  1.31768153,  0.31573178],
       [-0.54351777, -0.18146506, -2.50527471],
       [-1.29082627,  0.42580513, -0.03894887],
       [-0.99453561, -0.42545321, -1.3906943 ],
       [ 1.71742551,  0.4861858 ,  0.13854553]])

In [48]:
data[:,2]

array([ 1.21950139, -0.07196792,  0.40286579,  0.31573178, -2.50527471,
       -0.03894887, -1.3906943 ,  0.13854553])

In [41]:
names_Beom_mask = (names == 'Beom')
names_Beom_mask 

array([ True,  True, False, False, False,  True, False, False])

In [42]:
data[names_Beom_mask,:]

array([[ 0.40718539, -0.75447706,  0.00372776],
       [ 0.18056417,  0.44593076, -0.60284014],
       [-0.51010193,  0.68985343, -0.41696126]])

In [49]:
data[(names == 'Kim') | (names == 'Park'),:] 

array([[-1.36293573,  1.13901194,  0.40286579],
       [-0.99453561, -0.42545321, -1.3906943 ],
       [ 1.71742551,  0.4861858 ,  0.13854553]])

In [53]:
np.ceil(data)

array([[-0.,  1.,  2.],
       [ 1.,  1., -0.],
       [-1.,  2.,  1.],
       [-0.,  2.,  1.],
       [-0., -0., -2.],
       [-1.,  1., -0.],
       [-0., -0., -1.],
       [ 2.,  1.,  1.]])

In [54]:
arr1

array([[-0.,  1.,  2.],
       [ 1.,  1., -0.],
       [-1.,  2.,  1.],
       [-0.,  2.,  1.],
       [-0., -0., -2.],
       [-1.,  1., -0.],
       [-0., -0., -1.],
       [ 2.,  1.,  1.]])

In [56]:
# 행 합 ( 수직합)

np.sum(arr1, axis=0)

array([1., 8., 2.])

In [57]:
# 열 합 ( 수평 합)

np.sum(arr1, axis=1)

array([ 3.,  2.,  2.,  3., -2.,  0., -1.,  4.])

In [59]:
A = np.arange(6).reshape([2,3])
A

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
B = np.arange(3).reshape([1,3])
B

array([[0, 1, 2]])

In [65]:
A * B

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [66]:
B = np.arange(6).reshape([3,2])
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
np.matmul(A,B)

array([[10, 13],
       [28, 40]])

In [68]:
C = np.array([[1,2],[1,2],[1, 2]])
C

array([[1, 2],
       [1, 2],
       [1, 2]])

In [70]:
D = np.matmul(A,C)
D

array([[ 3,  6],
       [12, 24]])

In [71]:
D.shape

(2, 2)