In [ ]:
# ML lab 08: Tensor Manipulation 

In [1]:
import tensorflow as tf

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [4]:
# Simple Array

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [5]:
# 2D Array

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [7]:
# Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval()


array([4])

In [8]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [9]:
t = tf.constant([[[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [10]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [11]:
# Matmul VS multiply
 
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [12]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [ ]:
# Watch out broadcasting
 
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

In [ ]:
# Random values for variable initializations
 
tf.random_normal([3]).eval()

In [ ]:
tf.random_uniform([2]).eval()

In [ ]:
tf.random_uniform([2, 3]).eval()

In [ ]:
# Reduce Mean/Sum
 
tf.reduce_mean([1, 2], axis=0).eval()

In [ ]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

In [ ]:
tf.reduce_mean(x, axis=0).eval()

In [ ]:
tf.reduce_mean(x, axis=1).eval()

In [ ]:
tf.reduce_mean(x, axis=-1).eval()
tf.reduce_sum(x).eval()
tf.reduce_sum(x, axis=0).eval()
tf.reduce_sum(x, axis=-1).eval()
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

In [ ]:
# Argmax with axis
 
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

In [ ]:
tf.argmax(x, axis=1).eval()
tf.argmax(x, axis=-1).eval()

In [ ]:
# Reshape, squeeze, expand_dims
 
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

In [ ]:
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

In [ ]:
tf.squeeze([[0], [1], [2]]).eval()

In [ ]:
tf.expand_dims([0, 1, 2], 1).eval()

In [ ]:
# One hot
 
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

In [ ]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

In [ ]:
# casting
 
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

In [ ]:
# Stack
 
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

In [ ]:
tf.stack([x, y, z], axis=1).eval()

In [ ]:
# Ones like and Zeros like
 
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

In [ ]:
tf.zeros_like(x).eval()

In [ ]:
# Zip
 
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

In [ ]:
# Transpose
 
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

In [ ]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

In [ ]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

In [2]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])

In [3]:
tf.shape(t)
tf.rank(t)

<tf.Tensor 'Rank:0' shape=() dtype=int32>

In [4]:
sess = tf.Session()

In [5]:
print sess.run(tf.shape(t))
print sess.run(tf.size(t))
print sess.run(tf.rank(t))

SyntaxError: invalid syntax (<ipython-input-5-b555cff0b385>, line 1)

In [17]:
print sess.run(tf.size(t)).eval()
print sess.run(tf.rank(t)).eval()

SyntaxError: invalid syntax (<ipython-input-17-d525fb376bcc>, line 1)

In [23]:
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 4]])

In [24]:
tf.shape(t)
tf.rank(t)

<tf.Tensor 'Rank_5:0' shape=() dtype=int32>

In [25]:
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 4]])
sess = tf.Session()

print sess.run(tf.shape(t)).eval()
print sess.run(tf.size(t)).eval()
print sess.run(tf.rank(t)).eval()

SyntaxError: invalid syntax (<ipython-input-25-33989d87686f>, line 4)

In [29]:
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 4]])
sess = tf.InteractiveSession()

sess.run(tf.shape(t)) 

C:\anaconda\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([4, 3])

In [6]:
sess.run(tf.size(t))

24

In [34]:
sess.run(tf.rank(t)) 

4

In [35]:
sess.run(tf.shape(t))

array([1, 2, 3, 4])

In [41]:
x = [[[1.,2.,3.],[4.,5.,6.]],
     [[7.,8.,9.],[10.,11.,12.]]]

In [37]:
tf.reduce_mean(x).eval(Session=sess)

TypeError: eval() got an unexpected keyword argument 'Session'

In [38]:
tf.reduce_mean(x)

<tf.Tensor 'Mean_1:0' shape=() dtype=int32>

In [42]:
sess.run(tf.reduce_mean(x))

6.5

In [43]:
sess.run(tf.reduce_mean(x, axis=1))

array([[ 2.5,  3.5,  4.5],
       [ 8.5,  9.5, 10.5]], dtype=float32)

In [44]:
sess.run(tf.reduce_mean(x, axis=0))

array([[4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [46]:
with tf.Session() as sess:
    m1 = tf.constant([[3., 3.]])
    m2 = tf.constant([[2.],[2.]])
    product = tf.matmul(m1, m2)
    result = sess.run([product])
    print(result)

[array([[12.]], dtype=float32)]
